### ISSUE TITLE
Wiki or Github Pages?

### ISSUE THREAD

**Issue by kes1** [ScottishCities/1-opendatastandards#1]
I've created the repository, but github wiki's don't easily support pull requests for changes, so maybe we should use github pages instead which could support this if we want proper control.  I think github pages is slightly less accessible for people to edit though, compared to the WYSIWYG editor of the wikis. 

What do people think?

**Comment by watty62** [comment]
Did we resolve this @kes1 ? Was there a Wiki set up somewhere?

**Comment by stevenrevill** [comment]
@watty62 not sure if this is an answer or not but there is a lot of pages in the wiki tab at the top?  This is my first time using github in any real case so just learning my way around.
Steven

**Comment by kes1** [comment]
Hi @watty62 - yes we went with a Wiki for now, seems to have worked OK so please go ahead and add some knowledge in there :-)

**Comment by watty62** [comment]
Silly me - I'd not clicked through to the Wiki link. Now there. Thanks @kes1 @stevenrevill
